In [18]:
import pandas as pd

In [19]:
df = [{'Fellowship_ID':1001,'FirstName':'Frodo','Skills':'Hiding'},{'Fellowship_ID':1002,'FirstName':'Samwise','Skills':'Gardening'},{'Fellowship_ID':1003,'FirstName':'Gandalf','Skills':'Spells'},{'Fellowship_ID':1004,'FirstName':'Pippin','Skills':'Fireworks'}]
df

[{'Fellowship_ID': 1001, 'FirstName': 'Frodo', 'Skills': 'Hiding'},
 {'Fellowship_ID': 1002, 'FirstName': 'Samwise', 'Skills': 'Gardening'},
 {'Fellowship_ID': 1003, 'FirstName': 'Gandalf', 'Skills': 'Spells'},
 {'Fellowship_ID': 1004, 'FirstName': 'Pippin', 'Skills': 'Fireworks'}]

In [20]:
df1 =pd.DataFrame(df)
df1

   Fellowship_ID FirstName     Skills
0           1001     Frodo     Hiding
1           1002   Samwise  Gardening
2           1003   Gandalf     Spells
3           1004    Pippin  Fireworks

In [21]:
df = [{'Fellowship_ID':1001,'FirstName':'Frodo','Age':50},{'Fellowship_ID':1002,'FirstName':'Samwise','Age':39},{'Fellowship_ID':1006,'FirstName':'Legolas','Age':2931},{'Fellowship_ID':1007,'FirstName':'Elrond','Age':6520},{'Fellowship_ID':1008,'FirstName':'Barromir','Age':51}]
df2 = pd.DataFrame(df)
df2

   Fellowship_ID FirstName   Age
0           1001     Frodo    50
1           1002   Samwise    39
2           1006   Legolas  2931
3           1007    Elrond  6520
4           1008  Barromir    51

In [22]:
#inner join
df1.merge(df2)

   Fellowship_ID FirstName     Skills  Age
0           1001     Frodo     Hiding   50
1           1002   Samwise  Gardening   39

In [26]:
df1.merge(df2, on='Fellowship_ID', how='inner')

   Fellowship_ID FirstName_x     Skills FirstName_y  Age
0           1001       Frodo     Hiding       Frodo   50
1           1002     Samwise  Gardening     Samwise   39

In [27]:
df1.merge(df2, how = 'left')

   Fellowship_ID FirstName     Skills   Age
0           1001     Frodo     Hiding  50.0
1           1002   Samwise  Gardening  39.0
2           1003   Gandalf     Spells   NaN
3           1004    Pippin  Fireworks   NaN

In [28]:
df1.merge(df2, how = 'right')

   Fellowship_ID FirstName     Skills   Age
0           1001     Frodo     Hiding    50
1           1002   Samwise  Gardening    39
2           1006   Legolas        NaN  2931
3           1007    Elrond        NaN  6520
4           1008  Barromir        NaN    51

In [29]:
df1.merge(df2, how = 'outer')

   Fellowship_ID FirstName     Skills     Age
0           1001     Frodo     Hiding    50.0
1           1002   Samwise  Gardening    39.0
2           1003   Gandalf     Spells     NaN
3           1004    Pippin  Fireworks     NaN
4           1006   Legolas        NaN  2931.0
5           1007    Elrond        NaN  6520.0
6           1008  Barromir        NaN    51.0